defmodule Beeleex.Api do
  @moduledoc """
  This is in charge of interfacing with the Beelee GraphQL server
  To update data like Business Units, the Billing Center, companies or generate/update invoices
  """
  @behaviour Beeleex.ApiBehaviour

  require Logger

  defp url do
    Application.get_env(:beeleex, :beelee_endpoint, "https://beelee.geeks.solutions/v0-1/api")
  end

  defp headers do
    [
      {"content-type", "application/json"},
      {"secure-key", Application.get_env(:beeleex, :business_unit_secure_key)},
      {"bu-id", bu_id()}
    ]
  end

  # Headers for the user-facing back-office UI calls. Unlike the server-to-server
  # `headers/0` (which authenticates with the BU `secure-key`), these act on
  # behalf of the signed-in end user, so they relay that user's token via
  # `bu-authorization` alongside the `bu-id`. `token` is threaded from the
  # LiveView session (see `BeeleexWeb.LiveSession`).
  defp ui_headers(token) do
    headers = [
      {"content-type", "application/json"},
      {"bu-authorization", "Bearer " <> to_string(token)},
      {"bu-id", bu_id()}
    ]

    headers
  end

  # HTTPoison/hackney requires string header values — an integer `bu-id` would be
  # sent as a raw byte, not its digits. Always coerce to a string.
  defp bu_id, do: to_string(Application.get_env(:beeleex, :business_unit_id))

  # Beelee's GraphQL declares `$id: Int!`, so string ids (e.g. from URL params)
  # must be coerced to integers before being sent as variables.
  defp to_int(value) when is_integer(value), do: value
  defp to_int(value) when is_binary(value), do: String.to_integer(value)

  # Masks a secret for debug logging: keeps only the last 4 chars.
  defp mask(""), do: "<empty>"

  defp mask(value) when is_binary(value) do
    "***" <> String.slice(value, -4, 4) <> " (len=#{String.length(value)})"
  end

  @doc """
  This function will update invoices that were freshly generated by Beelee when a new cycle started
  """
  @spec update_invoices(list(Beeleex.InvoiceUpdate.t())) ::
          {:ok, String.t()} | {:error, String.t()}
  def update_invoices(invoices) when is_list(invoices) do
    company_invoices = Enum.map(invoices, &Beeleex.InvoiceUpdate.format_payload(&1))

    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             mutation updateCompanyInvoices($companyInvoices: [InvoiceInput]) {
               updateCompanyInvoices(companyInvoices: $companyInvoices) {
                 message
               }
             }
             """,
             variables: %{
               companyInvoices: company_invoices
             }
           },
           headers()
         ) do
      %{"data" => %{"updateCompanyInvoices" => %{"message" => message}}} ->
        {:ok, message}

      %{"data" => _, "errors" => errors} ->
        error = List.first(errors)["message"]
        Logger.error("#{__ENV__.function |> elem(0)}: #{error}")
        {:error, error}
    end
  end

  @doc """
  This function returns the company that is linked to your customer_project ID.
  It is helpful to update the company data related to a project in your Business Unit
  """
  @spec get_company_by_customer_project(String.t()) ::
          {:ok, Beeleex.Company.t()} | {:error, String.t()}
  def get_company_by_customer_project(customer_project) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             query getcompany($customer_project:String!){
               getCompanyByCustomerProject(customerProject:$customer_project) {
                   address{
                     city
                     country
                     postalCode
                     streetName
                   }
                   name
                   email
                   phoneNumber
                   customerProjects
                   vatNumber
                   businessUnit{
                     id
                     archived
                     name
                     billingCenter{
                       name
                       id
                       vatNumber
                     }
                     cycle
                     job{
                       scheduledAt
                     }
                   }
                   userId
                   id
                   solvencyStatus
                 }}
             """,
             variables: %{
               customer_project: customer_project
             }
           },
           headers()
         ) do
      %{"data" => %{"getCompanyByCustomerProject" => company}} ->
        company
        |> ExGeeks.Helpers.atomize_keys(transformer: &Macro.underscore/1)
        |> Beeleex.Company.compute_bu_cycle()
        |> then(fn company -> {:ok, struct(Beeleex.Company, company)} end)

      %{"data" => _, "errors" => errors} ->
        error = List.first(errors)["message"]
        Logger.error("#{__ENV__.function |> elem(0)}: #{error}")
        {:error, error}
    end
  end

  @doc """
  This function will create a new one time payment invoice on Beelee and immediately initiate a payment collection for this invoice
  """
  @spec generate_onetime_invoice(Beeleex.OnetimePayment.t()) ::
          {:ok, String.t()} | {:error, String.t()}
  def generate_onetime_invoice(onetime_payment) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             mutation generateInvoice($onetimeInvoice: OnetimeInvoiceInput) {
              generateOnetimeInvoice(companyInvoice: $onetimeInvoice) {
                id
                amount_before_tax
                tax_amount
                tax_rate
                amount_with_tax
                status
                type
                reduction_amount_before_tax
                reduction_tax_amount
                reduction_amount_with_tax
              }
             }
             """,
             variables: %{
               onetimeInvoice: onetime_payment
             }
           },
           headers()
         ) do
      %{"data" => %{"generateOnetimeInvoice" => invoice}} ->
        invoice
        |> ExGeeks.Helpers.atomize_keys(transformer: &Macro.underscore/1)
        |> then(fn company -> {:ok, struct(Beeleex.Invoice, company)} end)

      %{"data" => _, "errors" => errors} ->
        error = List.first(errors)["message"]
        Logger.error("#{__ENV__.function |> elem(0)}: #{error}")
        {:error, error}
    end
  end

  @doc """
  Loads up to 50 invoices for a company, the provided a project ID and a given tag in the current cycle
  """
  @spec get_current_cycle_invoices(String.t(), String.t(), String.t()) ::
          {:ok, list(Beeleex.Invoice.t())} | {:error, String.t()}
  def get_current_cycle_invoices(company_id, project_id, tag) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             query getInvoices($filter: [Filter], $size: Int, $skip: Int) {
               getInvoices(filter: $filter, size: $size, skip: $skip) {
                 invoices {
                   id
                   amount_before_tax
                   tax_amount
                   tax_rate
                   amount_with_tax
                   cycle
                   beginning
                   end
                   type
                   reduction_amount_before_tax
                   reduction_tax_amount
                   reduction_amount_with_tax
                   status
                   tags
                   breakdown {
                     projectId
                     packageName
                   }
                 }
                 count
                 total
               }
             }
             """,
             variables: %{
               filter: [
                 %{key: "company_id", value: "#{company_id}"},
                 %{key: "project_id", value: project_id},
                 %{key: "tag", value: tag}
               ],
               size: 50,
               current_cycle: true
             }
           },
           headers()
         ) do
      %{"data" => %{"getInvoices" => %{"count" => 0}}} ->
        {:error, "no_match"}

      %{"data" => %{"getInvoices" => %{"invoices" => invoices}}} ->
        invoices
        |> Enum.map(fn invoice ->
          invoice = ExGeeks.Helpers.atomize_keys(invoice, transformer: &Macro.underscore/1)
          struct(Beeleex.Invoice, invoice)
        end)
        |> then(fn invoices -> {:ok, invoices} end)

      %{"data" => _, "errors" => errors} ->
        error = List.first(errors)["message"]
        Logger.error("#{__ENV__.function |> elem(0)}: #{error}")
        {:error, error}
    end
  end

  @doc """
  Generate a new credit note, requires:
  - An amount in integer with the same decimal places as the originating invoice
  - The originating invoice id
  - A reason string
  - Optionally you can also provide a list of tags
  """
  @spec generate_credit_note(integer(), integer(), String.t(), list(String.t()) | nil) ::
          {:ok, Beeleex.CreditNote.t()} | {:error, String.t()}
  def generate_credit_note(amount, originating_invoice_id, reason, tags \\ []) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             mutation createCreditNote($CreditNote: CreditNoteInput!) {
              createCreditNote(CreditNote: $CreditNote) {
                id
                reason
                amount
                tags
                status
                remainingAmount
                originatingInvoice {
                  id
                  status
                }
              }
             }
             """,
             variables: %{
               CreditNote: %{
                 reason: reason,
                 amount: amount,
                 tags: tags,
                 originatingInvoiceId: originating_invoice_id
               }
             }
           },
           headers()
         ) do
      %{"data" => %{"createCreditNote" => %{"id" => _} = credit_note}} ->
        credit_note
        |> ExGeeks.Helpers.atomize_keys(transformer: &Macro.underscore/1)
        |> then(fn credit_note -> {:ok, struct(Beeleex.CreditNote, credit_note)} end)

      %{"data" => _, "errors" => errors} ->
        error = List.first(errors)["message"]
        Logger.error("#{__ENV__.function |> elem(0)}: #{error}")
        {:error, error}
    end
  end

  @doc """
  Loads up to 50 credit notes for the list of provided invoices
  """
  @spec get_credit_notes_for_invoices(String.t(), list(Invoice.t())) ::
          {:ok, list(CreditNote.t())} | {:error, String.t()}
  def get_credit_notes_for_invoices(company_id, invoices) do
    invoice_ids =
      invoices
      |> Stream.map(fn invoice -> invoice.id end)
      |> Enum.join(",")

    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             query getCreditNotes($Filters: [FlopFilter], $PageSize: Int, $Page: Int) {
              getCreditNotes(Filters: $Filters, Page: $Page, PageSize: $PageSize) {
                data {
                reason
                amount
                tags
                originating_invoice {
                  id
                  company {
                    id
                    business_unit {
                      id
                    }
                  }
                  }
                }
                count
                total
              }
             }
             """,
             variables: %{
               Filters: [
                 %{field: "credit_note_company", value: "#{company_id}"},
                 %{field: "originating_invoices", value: invoice_ids}
               ],
               PageSize: 50
             }
           },
           headers()
         ) do
      %{"data" => %{"getCreditNotes" => %{"data" => credit_notes}}} ->
        credit_notes
        |> Enum.map(fn credit_note ->
          credit_note =
            ExGeeks.Helpers.atomize_keys(credit_note, transformer: &Macro.underscore/1)

          struct(Beeleex.CreditNote, credit_note)
        end)
        |> then(fn credit_notes -> {:ok, credit_notes} end)

      %{"data" => _, "errors" => errors} ->
        error = List.first(errors)["message"]
        Logger.error("#{__ENV__.function |> elem(0)}: #{error}")
        {:error, error}
    end
  end

  @doc """
  Request a credit for a company and generates the credit notes for it
  based on the invoices in the current cycle.
  Returns an error if the BU has no cycles yet or if no valid company is found.
  """
  @spec request_credit_in_cycle(String.t(), integer(), String.t(), String.t(), list(String.t())) ::
          {:ok, list(CreditNote.t()), integer()} | {:error, String.t()}
  def request_credit_in_cycle(company_id, max_amount, search_tag, reason, tags) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             mutation requestCredit($companyId: Int, $maxAmount: Int!, $searchTag: String!, $reason: String, $tags: [String]) {
              requestCreditForCycle(companyId: $companyId, maxAmount: $maxAmount, searchTag: $searchTag, reason: $reason, tags: $tags) {
                creditNotes {
                  reason
                  amount
                  tags
                  originating_invoice {
                    id
                    type
                    status
                    amount_with_tax
                    company {
                      id
                      business_unit {
                        id
                      }
                    }
                  }
                }
                remainder
              }
             }
             """,
             variables: %{
               companyId: company_id,
               maxAmount: max_amount,
               searchTag: search_tag,
               reason: reason,
               tags: tags
             }
           },
           headers()
         ) do
      %{
        "data" => %{
          "requestCreditForCycle" => %{
            "creditNotes" => credit_notes,
            "remainder" => remainder
          }
        }
      } ->
        credit_notes
        |> Enum.map(fn credit_note ->
          credit_note =
            ExGeeks.Helpers.atomize_keys(credit_note, transformer: &Macro.underscore/1)

          struct(Beeleex.CreditNote, credit_note)
        end)
        |> then(fn credit_notes -> {:ok, credit_notes, remainder} end)

      %{"data" => _, "errors" => errors} ->
        error = List.first(errors)["message"]
        Logger.error("#{__ENV__.function |> elem(0)}: #{error}")
        {:error, error}
    end
  end

  # --------------------------------------------------------------------------
  # Company back-office UI operations
  #
  # These functions power the Beeleex LiveView pages. They act on behalf of the
  # signed-in end user, authenticating with `bu-authorization` (the user's
  # `user_portal` token, threaded in as the first argument) + `bu-id`. The token
  # never reaches the browser — it is read server-side from the LiveView session.
  #
  # The selected fields intentionally exclude secrets present in the Beelee
  # `Company` schema (e.g. `stripeSecretKey`, `secureKey`); only the data the
  # back-office UI needs is requested.
  # --------------------------------------------------------------------------

  @doc """
  List the companies of the Business Unit.

  `opts` accepts:
    * `:filter` - a list of Beelee `Filter` maps (defaults to `[]`)
    * `:size` - page size (defaults to `20`)
    * `:skip` - number of records to skip (defaults to `0`)

  Returns `{:ok, %{companies: [%Beeleex.Company{}], total: integer, count: integer}}`.
  """
  @spec get_companies(String.t(), keyword) ::
          {:ok, %{companies: list(Beeleex.Company.t()), total: integer, count: integer}}
          | {:error, String.t()}
  def get_companies(token, opts \\ []) do
    filter = Keyword.get(opts, :filter, [])
    size = Keyword.get(opts, :size, 20)
    skip = Keyword.get(opts, :skip, 0)

    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             query getCompanies($filter:[Filter], $size:Int, $skip:Int) {
               getCompanies(filter:$filter, size:$size, skip:$skip) {
                 companies { #{company_fields()} }
                 total
                 count
               }
             }
             """,
             variables: %{filter: filter, size: size, skip: skip}
           },
           ui_headers(token)
         ) do
      %{"data" => %{"getCompanies" => %{"companies" => companies} = result}} ->
        {:ok,
         %{
           companies: Enum.map(companies, &parse_company/1),
           total: result["total"] || 0,
           count: result["count"] || length(companies)
         }}

      response ->
        graphql_error(response, "get_companies")
    end
  end

  @doc """
  Fetch a single company by its Beelee id.
  """
  @spec get_company(String.t(), integer | String.t()) ::
          {:ok, Beeleex.Company.t()} | {:error, String.t()}
  def get_company(token, id) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             query getCompany($id:Int!) {
               getCompany(id:$id) { #{company_fields()} }
             }
             """,
             variables: %{id: to_int(id)}
           },
           ui_headers(token)
         ) do
      %{"data" => %{"getCompany" => company}} when not is_nil(company) ->
        {:ok, parse_company(company)}

      response ->
        graphql_error(response, "get_company")
    end
  end

  @doc """
  Create a company. `company_input` must match the Beelee `CompanyInput` shape
  (camelCase keys, e.g. `%{name:, email:, phoneNumber:, vatNumber:, address: %{...}}`).
  """
  @spec create_company(String.t(), map) :: {:ok, Beeleex.Company.t()} | {:error, String.t()}
  def create_company(token, company_input) do
    mutate_company(
      token,
      """
      mutation createCompany($company:CompanyInput!) {
        createCompany(company:$company) { #{company_fields()} }
      }
      """,
      %{company: company_input},
      "createCompany",
      "create_company"
    )
  end

  @doc """
  Update the company identified by `id` with the given `CompanyInput` map.
  """
  @spec update_company(String.t(), integer | String.t(), map) ::
          {:ok, Beeleex.Company.t()} | {:error, String.t()}
  def update_company(token, id, company_input) do
    mutate_company(
      token,
      """
      mutation editCompany($company:CompanyInput!, $id:Int!) {
        editCompany(company:$company, id:$id) { #{company_fields()} }
      }
      """,
      %{company: company_input, id: id},
      "editCompany",
      "update_company"
    )
  end

  @doc """
  Delete the company identified by `id`. Returns `{:ok, message}`.
  """
  @spec delete_company(String.t(), integer | String.t()) ::
          {:ok, String.t()} | {:error, String.t()}
  def delete_company(token, id) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             mutation deleteCompany($id:Int!) {
               deleteCompany(id:$id) { message }
             }
             """,
             variables: %{id: to_int(id)}
           },
           ui_headers(token)
         ) do
      %{"data" => %{"deleteCompany" => %{"message" => message}}} ->
        {:ok, message}

      response ->
        graphql_error(response, "delete_company")
    end
  end

  @doc """
  Return the customer projects that are available to link (i.e. not yet linked
  to any company). `project_ids` is the list of candidate `CustomerProject` ids.
  """
  @spec get_unlinked_projects(String.t(), list(String.t())) ::
          {:ok, list(String.t())} | {:error, String.t()}
  def get_unlinked_projects(token, project_ids) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             query getUnlinkedProjects($projectIds: [CustomerProject]) {
               getUnlinkedProjects(projectIds: $projectIds)
             }
             """,
             variables: %{projectIds: project_ids}
           },
           ui_headers(token)
         ) do
      %{"data" => %{"getUnlinkedProjects" => projects}} ->
        {:ok, projects || []}

      response ->
        graphql_error(response, "get_unlinked_projects")
    end
  end

  @doc """
  Link one or more customer projects to the company identified by `id`.
  `project_ids` is a list of `CustomerProject` values.
  """
  @spec link_projects(String.t(), integer | String.t(), list) ::
          {:ok, Beeleex.Company.t()} | {:error, String.t()}
  def link_projects(token, id, project_ids) do
    mutate_company(
      token,
      """
      mutation linkCustomerProject($id:Int!, $projectIds: [CustomerProject]) {
        linkCustomerProject(id:$id, projectIds: $projectIds) { #{company_fields()} }
      }
      """,
      %{id: id, projectIds: project_ids},
      "linkCustomerProject",
      "link_projects"
    )
  end

  @doc """
  Unlink a single customer project from the company identified by `id`.
  """
  @spec unlink_project(String.t(), integer | String.t(), any) ::
          {:ok, Beeleex.Company.t()} | {:error, String.t()}
  def unlink_project(token, id, project_id) do
    mutate_company(
      token,
      """
      mutation unlinkCustomerProject($id:Int!, $projectId: CustomerProject) {
        unlinkCustomerProject(id:$id, projectId: $projectId) { #{company_fields()} }
      }
      """,
      %{id: id, projectId: project_id},
      "unlinkCustomerProject",
      "unlink_project"
    )
  end

  @doc """
  List invoices. `opts` accepts the same `:filter`, `:size` and `:skip` keys as
  `get_companies/1`. To scope invoices to a company, pass a `company_id` filter:

      Beeleex.Api.get_invoices(filter: [%{key: "company_id", value: to_string(company_id)}])

  Returns `{:ok, %{invoices: [%Beeleex.Invoice{}], total: integer, count: integer}}`.
  """
  @spec get_invoices(String.t(), keyword) ::
          {:ok, %{invoices: list(Beeleex.Invoice.t()), total: integer, count: integer}}
          | {:error, String.t()}
  def get_invoices(token, opts \\ []) do
    filter = Keyword.get(opts, :filter, [])
    size = Keyword.get(opts, :size, 20)
    skip = Keyword.get(opts, :skip, 0)

    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             query getInvoices($filter:[Filter], $size:Int, $skip:Int) {
               getInvoices(filter:$filter, size:$size, skip:$skip) {
                 total
                 count
                 invoices { #{invoice_fields()} }
               }
             }
             """,
             variables: %{filter: filter, size: size, skip: skip}
           },
           ui_headers(token)
         ) do
      %{"data" => %{"getInvoices" => %{"invoices" => invoices} = result}} ->
        {:ok,
         %{
           invoices: Enum.map(invoices, &parse_invoice/1),
           total: result["total"] || 0,
           count: result["count"] || length(invoices)
         }}

      response ->
        graphql_error(response, "get_invoices")
    end
  end

  @doc """
  Fetch a single invoice by its Beelee id.
  """
  @spec get_invoice(String.t(), integer | String.t()) ::
          {:ok, Beeleex.Invoice.t()} | {:error, String.t()}
  def get_invoice(token, id) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             query getInvoice($id:Int!) {
               getInvoice(id:$id) { #{invoice_fields()} }
             }
             """,
             variables: %{id: to_int(id)}
           },
           ui_headers(token)
         ) do
      %{"data" => %{"getInvoice" => invoice}} when not is_nil(invoice) ->
        {:ok, parse_invoice(invoice)}

      response ->
        graphql_error(response, "get_invoice")
    end
  end

  @doc """
  List a company's payment methods. `opts` accepts `:filter`, `:size`, `:skip`
  like `get_invoices/1`; scope to a company with a `company_id` filter.

  Returns `{:ok, %{payment_methods: [map], total: integer, count: integer}}`
  where each payment method is an atomized map (`:id`, `:status`, `:type`,
  `:default_payment_method`, `:stripe_card` => `%{:brand, :last4, :exp_month,
  :exp_year}`, ...).
  """
  @spec get_payment_methods(String.t(), keyword) ::
          {:ok, %{payment_methods: list(map), total: integer, count: integer}}
          | {:error, String.t()}
  def get_payment_methods(token, opts \\ []) do
    filter = Keyword.get(opts, :filter, [])
    size = Keyword.get(opts, :size, 20)
    skip = Keyword.get(opts, :skip, 0)

    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             query getPaymentMethods($filter:[Filter], $size:Int, $skip:Int) {
               getPaymentMethods(filter:$filter, size:$size, skip:$skip) {
                 count
                 total
                 paymentMethods {
                   id
                   type
                   status
                   attempt
                   defaultPaymentMethod
                   company { id name }
                   stripeCard { stripeId brand expMonth expYear last4 }
                 }
               }
             }
             """,
             variables: %{filter: filter, size: size, skip: skip}
           },
           ui_headers(token)
         ) do
      %{"data" => %{"getPaymentMethods" => %{"paymentMethods" => methods} = result}} ->
        {:ok,
         %{
           payment_methods:
             Enum.map(methods, fn method ->
               ExGeeks.Helpers.atomize_keys(method, transformer: &Macro.underscore/1)
             end),
           total: result["total"] || 0,
           count: result["count"] || length(methods)
         }}

      response ->
        graphql_error(response, "get_payment_methods")
    end
  end

  @doc """
  Request a Stripe SetupIntent so a new card can be added to the company
  identified by `company_id`. The returned `client_secret` and `publishable_key`
  are confirmed client-side with Stripe.js (see the Beeleex Stripe LiveView hook).
  """
  @spec request_setup_intent(String.t(), integer | String.t()) ::
          {:ok, %{client_secret: String.t(), publishable_key: String.t(), verified: boolean}}
          | {:error, String.t()}
  def request_setup_intent(token, company_id) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             mutation requestSetupIntent($id:Int!) {
               requestSetupIntent(id:$id) {
                 clientSecret
                 publishableKey
                 verified
               }
             }
             """,
             variables: %{id: company_id}
           },
           ui_headers(token)
         ) do
      %{"data" => %{"requestSetupIntent" => intent}} when not is_nil(intent) ->
        {:ok,
         %{
           client_secret: intent["clientSecret"],
           publishable_key: intent["publishableKey"],
           verified: intent["verified"]
         }}

      # Beelee returns a 500 (`{:error, %{"errors" => %{"detail" => ...}}}`) when it
      # cannot create the Stripe SetupIntent — almost always because Stripe is not
      # configured for this Business Unit. Surface an actionable message.
      {:error, %{"errors" => %{"detail" => _}}} = response ->
        Logger.error(
          "[beeleex] request_setup_intent raw Beelee response: " <>
            inspect(response, limit: :infinity, printable_limit: :infinity)
        )

        {:error,
         "Online payments aren't available yet for this account. " <>
           "Please contact your administrator to enable Stripe payments."}

      response ->
        graphql_error(response, "request_setup_intent")
    end
  end

  @doc """
  Deactivate the payment method identified by `id`. Returns `{:ok, status}`.
  """
  @spec deactivate_payment_method(String.t(), integer | String.t()) ::
          {:ok, String.t()} | {:error, String.t()}
  def deactivate_payment_method(token, id) do
    payment_method_status_mutation(
      token,
      """
      mutation deactivatePaymentMethod($id:Int!) {
        deactivatePaymentMethod(id:$id) { status }
      }
      """,
      %{id: id},
      "deactivatePaymentMethod",
      "deactivate_payment_method"
    )
  end

  @doc """
  Retry (reactivate) the payment method identified by `id`. Returns `{:ok, status}`.
  """
  @spec reactivate_payment_method(String.t(), integer | String.t()) ::
          {:ok, String.t()} | {:error, String.t()}
  def reactivate_payment_method(token, id) do
    payment_method_status_mutation(
      token,
      """
      mutation retryPaymentMethod($id:Int!) {
        retryPaymentMethod(id:$id) { status }
      }
      """,
      %{id: id},
      "retryPaymentMethod",
      "reactivate_payment_method"
    )
  end

  @doc """
  Make `payment_id` the default payment method for `company_id`.
  Returns `{:ok, type}`.
  """
  @spec make_default_payment_method(String.t(), integer | String.t(), integer | String.t()) ::
          {:ok, String.t()} | {:error, String.t()}
  def make_default_payment_method(token, company_id, payment_id) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{
             query: """
             mutation changeDefaultPaymentMethod($companyId:Int!, $paymentId:Int!) {
               changeDefaultPaymentMethod(companyId:$companyId, paymentMethodId:$paymentId) {
                 type
               }
             }
             """,
             variables: %{companyId: company_id, paymentId: payment_id}
           },
           ui_headers(token)
         ) do
      %{"data" => %{"changeDefaultPaymentMethod" => %{"type" => type}}} ->
        {:ok, type}

      response ->
        graphql_error(response, "make_default_payment_method")
    end
  end

  # -- shared helpers for the company UI operations --------------------------

  defp mutate_company(token, query, variables, data_key, fn_name) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{query: query, variables: variables},
           ui_headers(token)
         ) do
      %{"data" => %{^data_key => company}} when not is_nil(company) ->
        {:ok, parse_company(company)}

      response ->
        graphql_error(response, fn_name)
    end
  end

  defp parse_company(company) do
    company
    |> ExGeeks.Helpers.atomize_keys(transformer: &Macro.underscore/1)
    |> then(&struct(Beeleex.Company, &1))
  end

  defp parse_invoice(invoice) do
    invoice
    |> ExGeeks.Helpers.atomize_keys(transformer: &Macro.underscore/1)
    |> then(&struct(Beeleex.Invoice, &1))
  end

  defp payment_method_status_mutation(token, query, variables, data_key, fn_name) do
    case ExGeeks.Helpers.endpoint_post_callback(
           url(),
           %{query: query, variables: variables},
           ui_headers(token)
         ) do
      %{"data" => %{^data_key => %{"status" => status}}} ->
        {:ok, status}

      response ->
        graphql_error(response, fn_name)
    end
  end

  defp graphql_error(%{"errors" => errors} = response, fn_name) when is_list(errors) do
    error = List.first(errors)["message"]
    Logger.error("#{fn_name}: #{error}")

    Logger.error(
      "[beeleex] #{fn_name} raw Beelee response: " <>
        inspect(response, limit: :infinity, printable_limit: :infinity)
    )

    {:error, error}
  end

  defp graphql_error(response, fn_name) do
    Logger.error("#{fn_name}: unexpected response from Beelee")

    Logger.error(
      "[beeleex] #{fn_name} raw Beelee response: " <>
        inspect(response, limit: :infinity, printable_limit: :infinity)
    )

    {:error, "unexpected response from Beelee"}
  end

  # Non-sensitive company fields requested by the back-office UI.
  defp company_fields do
    """
    id
    name
    email
    phoneNumber
    vatNumber
    registrationNumber
    solvencyStatus
    userId
    customerProjects
    invoicesCount
    paymentMethodsCount
    address {
      city
      country
      postalCode
      streetName
      streetNumber
    }
    businessUnit {
      id
      name
      cycle
    }
    """
  end

  # Invoice fields requested by the back-office UI.
  defp invoice_fields do
    """
    id
    type
    status
    attempt
    cycle
    beginning
    end
    closing_date
    insertedAt
    decimalPlaces
    amountBeforeTax
    taxAmount
    taxRate
    amountWithTax
    reduction_amount_before_tax
    reduction_tax_amount
    reduction_amount_with_tax
    company {
      id
      name
    }
    breakdown {
      packageName
      packagePriceBeforeTax
      packageTax
      projectId
      projectName
      payAsYouGo {
        name
        description
        quantity
        unitPriceBeforeTax
        totalBeforeTax
        tax
      }
    }
    """
  end
end
